"""Command replay: the replica reproduces its own trajectories, windows re-sync."""

from pathlib import Path

import numpy as np
import pytest

pytest.importorskip("mujoco")

ROOT = Path(__file__).resolve().parents[2]
MJCF = ROOT / "assets/latent_playkit/model/g1_29dof_rev_1_0.xml"


def _plant():
    from embodied_control.lowlevel.command_replay import plant_from_profile
    from embodied_control.robot.plant import load_plant_config

    profile = load_plant_config(ROOT / "examples/g1_plant.yaml")
    names = profile.joint_names
    return plant_from_profile(
        str(MJCF), profile, names,
        [j.vendor_stiffness for j in profile.joints], [j.vendor_damping for j in profile.joints],
    ), names, profile


def test_replica_reproduces_itself_from_true_state():
    """A trajectory generated by the replica replays to itself: the tool's floor."""
    from embodied_control.lowlevel.command_replay import Recording, replay

    if not MJCF.is_file():
        pytest.skip("no G1 model")
    plant, names, profile = _plant()
    nominal = np.array([j.nominal_position for j in profile.joints])
    rng = np.random.default_rng(0)
    T = 60
    targets = nominal[None, :] + 0.15 * np.sin(np.linspace(0, 6, T))[:, None] * rng.uniform(0.2, 1.0, len(names))
    quat = np.array([0.0, 0.0, 0.0, 1.0])
    plant.set_state(nominal, np.zeros(len(names)), quat)
    measured = [plant.joint_pos()]
    for t in range(T - 1):
        plant.step_tick(targets[t], None)
        measured.append(plant.joint_pos())
    rec = Recording(
        joint_names=names, measured=np.array(measured), targets=targets,
        quat_xyzw=np.tile(quat, (T, 1)), anchor_pos=np.zeros((T, 3)),
        reference_frames=np.arange(T), source="synthetic",
    )
    result = replay(rec, plant, window_ticks=10, settle_ticks=2)
    err = np.abs(result.sim_pos[result.valid] - result.hw_pos[result.valid])
    # The synthetic recording carries no root translation, so each re-sync
    # starts the body at rest on the floor; the real plant control replay
    # (walking_quip_360, anchor-log init) sits at 0.010 rad leg MAE.
    assert np.nanmean(err) < 0.03
    assert result.per_joint()[names[0]]["mae_rad"] < 0.05
    rows = result.per_window()
    assert len(rows) >= 4 and all(r["leg_mae_rad"] < 0.05 for r in rows)


def test_lag_free_step_applies_the_new_target_each_tick():
    from embodied_control.lowlevel.command_replay import Recording, replay

    if not MJCF.is_file():
        pytest.skip("no G1 model")
    plant, names, profile = _plant()
    nominal = np.array([j.nominal_position for j in profile.joints])
    quat = np.array([0.0, 0.0, 0.0, 1.0])
    plant.set_state(nominal, np.zeros(len(names)), quat)
    # A target ramp on the left elbow: the lag-free replica must follow it,
    # not hold the first target (the bug the plant control replay exposed).
    i = names.index("left_elbow_joint")
    targets = np.tile(nominal, (30, 1))
    targets[:, i] = nominal[i] + np.linspace(0.0, 0.4, 30)
    lagged = None
    for t in range(29):
        lagged = plant.step_tick(targets[t], lagged)
    assert plant.joint_pos()[i] > nominal[i] + 0.25
